version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes: 
      - ./mosquitto_log:/mosquitto/log
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: host  # Use host network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/uptime"]
      interval: 60s
      timeout: 10s
      retries: 3

  mqtt_handler:
    build:
      context: ./
      dockerfile: Dockerfile.handler
    container_name: mqtt_handler
    volumes:
      - ./:/Handler
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER_HOST=localhost  # Use localhost since both are on the host network
      - MQTT_BROKER_PORT=1883
    network_mode: host  # Use host network
    working_dir: /Handler
    command: python3 handler.py

volumes:
  mosquitto_log:
  mosquitto_data: