version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    volumes: 
      - ./mosquitto_log:/mosquitto/log
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/uptime"]
      interval: 60s
      timeout: 10s
      retries: 3

    restart: always

volumes:
  mosquitto_log:
  mosquitto_data: