# syntax=docker/dockerfile:1
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /Handler


# ENTRYPOINT [ "python3", "handler.py" ]
